[package]
name = "rust-server-learning"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["net", "rt-multi-thread", "macros", "time", "signal"] }
axum = "0.8"
tower-http = { version = "0.6", features = ["timeout"] }

[dev-dependencies]
tracing-test = { version = "0.2", features = ["no-env-filter"] }
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1.5"
